# This file was generated by GoReleaser. DO NOT EDIT.
cask "kervo" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "55713654020fb4085864322ae34573cc24adbd43272d275829bdee6691063b92"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "225211e00ffb5f0d6245f1befb1c1aa9ad05d403e302f81ade42413d34d78c44"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a686e7697dd2cf18a556836292022c1053fbd0bcb3d186a3a68f499b4c8e233"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d27555d4f27ad013a5c50be88b12ef4990ccbabc1fd88ac81443683f4cc22a9a"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kervo"
  desc "Deterministic context for non-deterministic agents"
  homepage "https://github.com/kervo-os/kervo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kervo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kervo"]
    end
  end

  # No zap stanza required

end
