# This file was generated by GoReleaser. DO NOT EDIT.
cask "kervo" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "e16b1282ec70c64282dcdd9fe36ecf6d509f9a010a81e33b914f8f8d94b5bd61"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b069329cf2a287291499fd52abd3a847dde739f6d8175dff82d94fdceacb477a"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3526ee71e866e44e54b6f917d5e716cc206f068aa7cebad4f56393abd30ac4a"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6aa66d7e98f259ba002a1aa9a0c0dc22d0038d4e07b9b23053f0bf7de25de8e"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kervo"
  desc "Deterministic context for non-deterministic agents"
  homepage "https://github.com/kervo-os/kervo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kervo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kervo"]
    end
  end

  # No zap stanza required

end
