# This file was generated by GoReleaser. DO NOT EDIT.
cask "kervo" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "38106a05098e6a401dc5bc634675e081379bc0b5b9890316f01fe43b98971c2e"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d335619996ffa0ea9b956d30430658977dcab6cad5d3b255a9a60d27b567f120"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea2b0aad860690bc0d18822179cda744b66c62cf484d7105a6dc30df7c1e7d84"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b4a892591efe5722e5d4cde33ca3f485b6e1361a11442071f3f6bfa8d3201d5"
      url "https://github.com/kervo-os/kervo/releases/download/v#{version}/kervo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kervo"
  desc "Deterministic context for non-deterministic agents"
  homepage "https://github.com/kervo-os/kervo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kervo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kervo"]
    end
  end

  # No zap stanza required

end
